codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: 'reach,diff,flags,tree,reach'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_critical_paths: false

flags:
  unittests:
    paths:
      - src/

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
